title = "toprch"
baseURL = "https://toprch.github.io/docs/"
tags = ["toprch"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "toprch"
  author = "toprch"
  description = "toprch"
  logoBig = ""
  logoSmall = ""
  favicon = "favicon.ico"
  opengraphImage = ""
  email = ""
  googleTagManger = ""
  customCSS = false

  # Social media links in footer
  twitter = ""
  linkedin = ""
  github = "github.com/toprch"
  facebook = ""

  # Copyright and theme author credit in footer
  copyright = true
  credit = true

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = ""

[[menu.main]]
  name = "Blog"
  url  = "/#blog"
  weight = 1
#[[menu.main]]
#  name = "Work"
#  url  = "/#work"
#  weight = 2
[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 3
#[[menu.main]]
#  name = "Contact"
#  url  = "/#contact"
#  weight = 4
